### ISSUE TITLE
Check readme file

### ISSUE THREAD

**Issue by Richie9000** [ayebaishmo/portifolio_mobile_version#10]
Good job so far!

One thing to add to your read me file, is more information about you for example: your twitter account.

Happy coding!

**Comment by ayebaishmo** [comment]
Yap, There is need to add handle on it, I will surely add that. Thank you

**Comment by eri8-9** [comment]
Also, modify in your README file the word "portifolio" is grammatically incorrect in the English language instead use "Portfolio" Cheers! 🙂

**Comment by ayebaishmo** [comment]
Yes that to, I will surely change that thank you
